# .streamlit/config.toml

[server]
headless = true
enableCORS = false
port = 8501

[theme]
primaryColor = "#0E1117"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
showSidebarNavigation = false

[ui]
pageTitle = "📊 Sector Exception Tracker"
